SUPABASE_URL = "https://bgdsytssdeitrrrknvfb.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJnZHN5dHNzZGVpdHJycmtudmZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1NDA1NzQsImV4cCI6MjA3ODExNjU3NH0.Qtdebvn-e1m-r3SvOmzAzqKk3k2MHs_QFA-CEe9pKrY"
